name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/terraform-github-actions@master
        
      - name: Initialize Terraform
        run: terraform init
        
      - name: Apply Terraform changes
        run: terraform apply -auto-approve
